% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=HeatedSeats_SUV_LC_High
v1=12.2;
v2=13.5;
v3=14.5;
c1=14.5;
c2=15.9;
c3=17.4;
Data=([v1 v2 v3 c1 c2 c3]);