% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=HeatedSeats_SUV_LC_Low
v1=12.2;
v2=13.5;
v3=14.5;
c1=3.5;
c2=3.9;
c3=4.2;
Data=([v1 v2 v3 c1 c2 c3]);