% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=HeatedSeats_SUV_LC_2Low
v1=12.2;
v2=13.5;
v3=14.5;
c1=7;
c2=7.8;
c3=8.4;
Data=([v1 v2 v3 c1 c2 c3]);