% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=ComboLoads_Large_Car_LC_City_Summer_Day
v1=12.2;
v2=13.5;
v3=14.5;
c1=67.6;
c2=74.0;
c3=80.1;
Data=([v1 v2 v3 c1 c2 c3]);