% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=ComboLoads_Large_Car_LC_Country_Summer_Night
v1=12.2;
v2=13.5;
v3=14.5;
c1=47.2;
c2=51.6;
c3=55.3;
Data=([v1 v2 v3 c1 c2 c3]);