% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=ComboLoads_Large_Car_LC_Foul_Summer_Night
v1=12.2;
v2=13.5;
v3=14.5;
c1=71.9;
c2=79.6;
c3=85.8;
Data=([v1 v2 v3 c1 c2 c3]);