% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=Radio_Sub_Compact_Car_LC_Two
v1=12.2;
v2=13.5;
v3=14.5;
c1=0.2;
c2=0.2;
c3=0.2;
Data=([v1 v2 v3 c1 c2 c3]);