% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=Radio_Large_Car_LC_One
v1=12.2;
v2=13.5;
v3=14.5;
c1=.7;
c2=.7;
c3=.6;
Data=([v1 v2 v3 c1 c2 c3]);