function fig = gui_plot_control()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

h=findobj('tag','plot control');
if isempty(h)
   
   figure_color=[0.8 0.8 0.8];
   
   if get(0,'screensize')==[1 1 1024 768]
      posfig=[907 397 107 199];
   else
      posfig=[690 300 107 199];
   end
   
   h0 = figure('Color',figure_color, ...
      'MenuBar','none', ...
      'NumberTitle','off', ...
      'Name','Plot Control--ADVISOR',...
      'Position',posfig, ...
      'Tag','plot control');
   h1 = uicontrol('Parent',h0, ...
      'CallBack','figure(findobj(''tag'',''results_figure''));hold on;set(findobj(''tag'',''hold off''),''value'',0)',...
      'BackgroundColor',figure_color, ...
      'Position',[17 174 60 19], ...
      'String','hold on', ...
      'Style','radiobutton', ...
      'Tag','hold on');
   h1 = uicontrol('Parent',h0, ...
      'BackgroundColor',figure_color, ...
      'CallBack','figure(findobj(''tag'',''results_figure''));hold off;set(findobj(''tag'',''hold on''),''value'',0)',...
      'Position',[17 152 60 20], ...
      'String','hold off', ...
      'Style','radiobutton', ...
      'Tag','hold off');
   h1 = uicontrol('Parent',h0, ...
      'BackgroundColor',figure_color, ...
      'Position',[17 117 60 20], ...
      'CallBack','figure(findobj(''tag'',''results_figure''));zoom on;set(findobj(''tag'',''zoom off''),''value'',0)',...
      'String','zoom on', ...
      'Style','radiobutton', ...
      'Tag','zoom on');
   h1 = uicontrol('Parent',h0, ...
      'BackgroundColor',figure_color, ...
      'CallBack','figure(findobj(''tag'',''results_figure''));zoom off;set(findobj(''tag'',''zoom on''),''value'',0)',...
      'Position',[17 96 60 20], ...
      'String','zoom off', ...
      'Style','radiobutton', ...
      'Tag','zoom off');
   h1 = uicontrol('Parent',h0, ...
      'Callback','figure(findobj(''tag'',''results_figure''));legend off',...
      'Position',[17 45 60 20], ...
      'String','legend off', ...
      'Tag','legend off');
   h1 = uicontrol('Parent',h0, ...
      'callback','figure(findobj(''tag'',''results_figure''));xlim(''auto'');ylim(''auto'');',...
      'Position',[17 73 60 19], ...
      'String','zoom reset', ...
      'Tag','zoom reset');
   h1 = uicontrol('Parent',h0, ...
      'callback','figure(findobj(''tag'',''results_figure''));grid',...
      'Position',[10 14 88 23], ...
      'String','grid toggle on/off', ...
      'Tag','Pushbutton2');
else
   figure(h)
end

if nargout > 0, fig = h0; end

%revision history
%12/2/98-ss added if statements at the beginning for different screen resolutions
%6/8/99-ss,vhj made it so if figure already exists it just makes it current instead of
%           creating another one.