% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=ComboLoads_Sub_Compact_Car_LC_City_Winter_Night
v1=12.2;
v2=13.5;
v3=14.5;
c1=30.6;
c2=33.7;
c3=35.8;
Data=([v1 v2 v3 c1 c2 c3]);