% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=ComboLoads_Sub_Compact_Car_LC_Country_Summer_Night
v1=12.2;
v2=13.5;
v3=14.5;
c1=38;
c2=41.9;
c3=44.6;
Data=([v1 v2 v3 c1 c2 c3]);