% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=RearDefrost_Large_Car
v1=12.2;
v2=13.5;
v3=14.5;
c1=26.6;
c2=29.1;
c3=31.4;
Data=([v1 v2 v3 c1 c2 c3]);