% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=Mid_Sized_Car_3
v1=12.2;
v2=13.5;
v3=14.5;
c1=18.4;
c2=20.1;
c3=21.4;
Data=([v1 v2 v3 c1 c2 c3]);