% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=Sub_Compact_Car_3
v1=12.2;
v2=13.5;
v3=14.5;
c1=16.6;
c2=18.3;
c3=19.5;
Data=([v1 v2 v3 c1 c2 c3]);