% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=RearDefrost_Sub_Compact_Car
v1=12.2;
v2=13.5;
v3=14.5;
c1=18.8;
c2=20.7;
c3=22;
Data=([v1 v2 v3 c1 c2 c3]);