% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=ComboLoads_Mid_Sized_Car_LC_City_Summer_Day
v1=12.2;
v2=13.5;
v3=14.5;
c1=57.1;
c2=64.3;
c3=68.7;
Data=([v1 v2 v3 c1 c2 c3]);