% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=ComboLoads_Mid_Sized_Car_LC_Foul_Winter_Night
v1=12.2;
v2=13.5;
v3=14.5;
c1=58.8;
c2=64.3;
c3=67.7;
Data=([v1 v2 v3 c1 c2 c3]);