% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=TurnSignals_Mid_Sized_Car
v1=12.2;
v2=13.5;
v3=14.5;
c1=6.7;
c2=7.1;
c3=7.3;
Data=([v1 v2 v3 c1 c2 c3]);