% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=HeatedSeats_Large_Car_LC_Low
v1=12.2;
v2=13.5;
v3=14.5;
c1=6.6;
c2=7.3;
c3=7.8;
Data=([v1 v2 v3 c1 c2 c3]);