% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=Radio_Mid_Sized_Car_LC_One
v1=12.2;
v2=13.5;
v3=14.5;
c1=1.7;
c2=1.8;
c3=1.7;
Data=([v1 v2 v3 c1 c2 c3]);