% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=Radio_Mid_Sized_Car_LC_Two
v1=12.2;
v2=13.5;
v3=14.5;
c1=3.4;
c2=3.6;
c3=3.4;
Data=([v1 v2 v3 c1 c2 c3]);