% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=Mid_Sized_Car_3
v1=12.2;
v2=13.5;
v3=14.5;
c1=20.6;
c2=23.3;
c3=25.1;
Data=([v1 v2 v3 c1 c2 c3]);