% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=Engine_Mid_Sized_Car
v1=12.2;
v2=13.5;
v3=14.5;
c1=14.6;
c2=15.5;
c3=15.6;
Data=([v1 v2 v3 c1 c2 c3]);