% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=ComboLoads_SUV_LC_City_Summer_Day
v1=12.2;
v2=13.5;
v3=14.5;
c1=42.5;
c2=47.3;
c3=50.7;
Data=([v1 v2 v3 c1 c2 c3]);