% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=ComboLoads_SUV_LC_City_Winter_Night
v1=12.2;
v2=13.5;
v3=14.5;
c1=49.9;
c2=54.1;
c3=58;
Data=([v1 v2 v3 c1 c2 c3]);