% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=ComboLoads_SUV_LC_Country_Summer_Night
v1=12.2;
v2=13.5;
v3=14.5;
c1=54.8;
c2=60.3;
c3=64.1;
Data=([v1 v2 v3 c1 c2 c3]);