% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=Sub_Compact_Car_Ave
v1=12.2;
v2=13.5;
v3=14.5;
c1=2.5;
c2=2.8;
c3=3.1;
Data=([v1 v2 v3 c1 c2 c3]);