% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=FrontWipers_Sub_Compact_Car
v1=12.2;
v2=13.5;
v3=14.5;
c1=2.1;
c2=2.2;
c3=2.5;
Data=([v1 v2 v3 c1 c2 c3]);