% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=Misc_Mid_Sized_Car
v1=12.2;
v2=13.5;
v3=14.5;
c1=4.2;
c2=4.5;
c3=4.7;
Data=([v1 v2 v3 c1 c2 c3]);