% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=BrakeLights_Sub_Compact_Car
v1=12.2;
v2=13.5;
v3=14.5;
c1=6.5;
c2=6.8;
c3=7.1;
Data=([v1 v2 v3 c1 c2 c3]);