% This file is generated by CreateModelFile.m
%     It stores data for specific models
function [Data]=ExternalLights_Mid_Sized_Car_LC_Day_Lights
v1=12.2;
v2=13.5;
v3=14.5;
c=[3.8	4.0	4.2];
Data=([v1 v2 v3 c]);